
#libsigrokdecode4DSL
#LIBSIGROKDECODE4DSL


FIND_PATH(LIBSIGROKDECODE4DSL_INCLUDE_DIR libsigrokdecode4DSL/libsigrokdecode.h
		/usr/local/include/
		/usr/include/)
	

FIND_LIBRARY(LIBSIGROKDECODE4DSL_LIBRARY libsigrokdecode4DSL.a 
		/usr/local/lib/
		/usr/lib/)
		
if (LIBSIGROKDECODE4DSL_INCLUDE_DIR AND LIBSIGROKDECODE4DSL_LIBRARY)
	set (LIBSIGROKDECODE4DSL_FOUND TRUE)
	message("set LIBSIGROKDECODE4DSL_FOUND true")
endif(LIBSIGROKDECODE4DSL_INCLUDE_DIR AND LIBSIGROKDECODE4DSL_LIBRARY)
